language: python
dist: xenial
sudo: false

addons:
  chrome: stable

cache:
  pip: true

env:
  global:
    - PATH=$HOME/bin:$PATH

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-dj111 }
    - { python: 2.7, env: TOXENV=py27-dj111-grp }
    - { python: 3.7, env: TOXENV=py37-dj111 }
    - { python: 3.7, env: TOXENV=py37-dj20 }
    - { python: 3.7, env: TOXENV=py37-dj20-grp }
    - { python: 3.7, env: TOXENV=py37-dj21 }
    - { python: 3.7, env: TOXENV=py37-dj21-grp }
    - { python: 3.7, env: TOXENV=py37-dj22 }
    - { python: 3.7, env: TOXENV=py37-dj22-grp }
    - { python: 3.7, env: TOXENV=py37-dj30 }
    - { python: 3.7, env: TOXENV=py37-dj30-grp }

install:
  - pip install tox 

before_script:
  - mkdir -p ~/bin
  - |
    if [ ! -e ~/bin/chromedriver ]; then
      export CHROMEDRIVER_VERSION=$(curl -q http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
      wget -N http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -P ~/
      unzip ~/chromedriver_linux64.zip -d ~/bin
      rm ~/chromedriver_linux64.zip
      chmod +x ~/bin/chromedriver
    fi

script:
  - travis_retry tox -- --selenium=chrome-headless --verbosity=3 --failfast
