name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.8"
            django-version: "4.2"
            grappelli: "0"
          - python-version: "3.9"
            django-version: "4.2"
            grappelli: "1"
          - python-version: "3.11"
            django-version: "5.1"
            grappelli: "1"
          - python-version: "3.13"
            django-version: "5.2"
            grappelli: "0"

    name: Django ${{ matrix.django-version }} (Python ${{ matrix.python-version }})${{ matrix.grappelli == '1' && ' + grappelli' || '' }}

    env:
      DJANGO: ${{ matrix.django-version }}
      GRAPPELLI: ${{ matrix.grappelli }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: |
        tox -- -v2 --selenium=chrome-headless || \
        tox -- -v2 --selenium=chrome-headless || \
        tox -- -v2 --selenium=chrome-headless
